baseURL = "https://ckolumbus.github.io/"

title = "CKolumbus' Blog"
theme = "mainroad"

languageCode = "en-us"
paginate = 10 # Number of posts per page
disablePathToLower = false
disqusShortname = "ckolumbusgithub" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author] # Used in authorbox
    name = "Chris Drexler"
    bio = "xxxx"
    avatar = "img/ckolumbus.jpg"

[Params]
    author = "Chris Drexler" # Author's name (appears in meta tags and under posts)
    subtitle = "development rumblings: linux, python, go, C#, .Net Core, arduino and more" # Subtitle of your site. Used in site header
    description = "development rumblings: linux, python, go, C#, .Net Core, arduino and more" # Description of your site. Used in meta description
    opengraph = true # Enable OpenGraph if true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = false # Show authorbox at bottom of pages if true
    post_navigation = true # Show post navigation at bottom of pages if true
    postSections = ["post"] # the section pages to show on home page and the "Recent articles" widget
    #postSections = ["blog", "news"] # alternative that shows more than one section's pages
    #dateformat = "2006-01-02" # change the format of dates
    truncate = true # If false, all of blog post will appear on front page (and in pagination)
    #sectionPagesMenu = "main"


[permalinks]
  posts = "posts/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"

[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 5 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

    # Enable "Social" widget, if any of "social_*" set a value
    social_github = "CKolumbus"
    social_twitter = "CKolumbus_"
    #social_email = "ckolumbus@ac-drexler.de"
    #social_facebook = "username"
    #social_linkedin = "username"
    #social_google_plus = "115219256126192429022"


